[workspace]
resolver = "2"
members = [
    "cmp_any",
    "display_container",
    "gazebo",
    "gazebo_derive",
    "dupe",
    "dupe_derive",
]

[workspace.dependencies]
either = "1.8"
indenter = "0.3.3"
