[package]
authors = ["Facebook"]
categories = ["rust-patterns"]
description = "Derive Dupe"
documentation = "https://docs.rs/dupe"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "dupe_derive"
repository = "https://github.com/facebookincubator/gazebo"
version = "0.9.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.3"
syn = { version = "2", features = ["extra-traits"] }
